// Base de dados completa de Estados e Municípios do Brasil
export interface Estado {
  sigla: string
  nome: string
}

export const estados: Estado[] = [
  { sigla: "AC", nome: "Acre" },
  { sigla: "AL", nome: "Alagoas" },
  { sigla: "AP", nome: "Amapá" },
  { sigla: "AM", nome: "Amazonas" },
  { sigla: "BA", nome: "Bahia" },
  { sigla: "CE", nome: "Ceará" },
  { sigla: "DF", nome: "Distrito Federal" },
  { sigla: "ES", nome: "Espírito Santo" },
  { sigla: "GO", nome: "Goiás" },
  { sigla: "MA", nome: "Maranhão" },
  { sigla: "MT", nome: "Mato Grosso" },
  { sigla: "MS", nome: "Mato Grosso do Sul" },
  { sigla: "MG", nome: "Minas Gerais" },
  { sigla: "PA", nome: "Pará" },
  { sigla: "PB", nome: "Paraíba" },
  { sigla: "PR", nome: "Paraná" },
  { sigla: "PE", nome: "Pernambuco" },
  { sigla: "PI", nome: "Piauí" },
  { sigla: "RJ", nome: "Rio de Janeiro" },
  { sigla: "RN", nome: "Rio Grande do Norte" },
  { sigla: "RS", nome: "Rio Grande do Sul" },
  { sigla: "RO", nome: "Rondônia" },
  { sigla: "RR", nome: "Roraima" },
  { sigla: "SC", nome: "Santa Catarina" },
  { sigla: "SP", nome: "São Paulo" },
  { sigla: "SE", nome: "Sergipe" },
  { sigla: "TO", nome: "Tocantins" },
]

export const municipiosPorEstado: Record<string, string[]> = {
  MA: [
    "AÇAILÂNDIA",
    "AFONSO CUNHA",
    "ÁGUA DOCE DO MARANHÃO",
    "ALCÂNTARA",
    "ALDEIAS ALTAS",
    "ALTAMIRA DO MARANHÃO",
    "ALTO ALEGRE DO MARANHÃO",
    "ALTO ALEGRE DO PINDARÉ",
    "ALTO PARNAÍBA",
    "AMAPÁ DO MARANHÃO",
    "AMARANTE DO MARANHÃO",
    "ANAJATUBA",
    "ANAPURUS",
    "APICUM-AÇU",
    "ARAGUANÃ",
    "ARAIOSES",
    "ARAME",
    "ARARI",
    "AXIXÁ",
    "BACABAL",
    "BACABEIRA",
    "BACURI",
    "BACURITUBA",
    "BALSAS",
    "BARÃO DE GRAJAÚ",
    "BARRA DO CORDA",
    "BARREIRINHAS",
    "BELÁGUA",
    "BELA VISTA DO MARANHÃO",
    "BENEDITO LEITE",
    "BEQUIMÃO",
    "BERNARDO DO MEARIM",
    "BOA VISTA DO GURUPI",
    "BOM JARDIM",
    "BOM JESUS DAS SELVAS",
    "BOM LUGAR",
    "BREJO",
    "BREJO DE AREIA",
    "BURITI",
    "BURITI BRAVO",
    "BURITICUPU",
    "BURITIRANA",
    "CACHOEIRA GRANDE",
    "CAJAPIÓ",
    "CAJARI",
    "CAMPESTRE DO MARANHÃO",
    "CÂNDIDO MENDES",
    "CANTANHEDE",
    "CAPINZAL DO NORTE",
    "CAROLINA",
    "CARUTAPERA",
    "CAXIAS",
    "CEDRAL",
    "CENTRAL DO MARANHÃO",
    "CENTRO DO GUILHERME",
    "CENTRO NOVO DO MARANHÃO",
    "CHAPADINHA",
    "CIDELÂNDIA",
    "CODÓ",
    "COELHO NETO",
    "COLINAS",
    "CONCEIÇÃO DO LAGO-AÇU",
    "COROATÁ",
    "CURURUPU",
    "DAVINÓPOLIS",
    "DOM PEDRO",
    "DUQUE BACELAR",
    "ESPERANTINÓPOLIS",
    "ESTREITO",
    "FEIRA NOVA DO MARANHÃO",
    "FERNANDO FALCÃO",
    "FORMOSA DA SERRA NEGRA",
    "FORTALEZA DOS NOGUEIRAS",
    "FORTUNA",
    "GODOFREDO VIANA",
    "GONÇALVES DIAS",
    "GOVERNADOR ARCHER",
    "GOVERNADOR EDISON LOBÃO",
    "GOVERNADOR EUGÊNIO BARROS",
    "GOVERNADOR LUIZ ROCHA",
    "GOVERNADOR NEWTON BELLO",
    "GOVERNADOR NUNES FREIRE",
    "GRAÇA ARANHA",
    "GRAJAÚ",
    "GUIMARÃES",
    "HUMBERTO DE CAMPOS",
    "ICATU",
    "IGARAPÉ DO MEIO",
    "IGARAPÉ GRANDE",
    "IMPERATRIZ",
    "ITAIPAVA DO GRAJAÚ",
    "ITAPECURU MIRIM",
    "ITINGA DO MARANHÃO",
    "JATOBÁ",
    "JENIPAPO DOS VIEIRAS",
    "JOÃO LISBOA",
    "JOSELÂNDIA",
    "JUNCO DO MARANHÃO",
    "LAGO DA PEDRA",
    "LAGO DO JUNCO",
    "LAGO DOS RODRIGUES",
    "LAGO VERDE",
    "LAGOA DO MATO",
    "LAGOA GRANDE DO MARANHÃO",
    "LAJEADO NOVO",
    "LIMA CAMPOS",
    "LORETO",
    "LUÍS DOMINGUES",
    "MAGALHÃES DE ALMEIDA",
    "MARACAÇUMÉ",
    "MARAJÁ DO SENA",
    "MARANHÃOZINHO",
    "MATA ROMA",
    "MATINHA",
    "MATÕES",
    "MATÕES DO NORTE",
    "MILAGRES DO MARANHÃO",
    "MIRADOR",
    "MIRANDA DO NORTE",
    "MIRINZAL",
    "MONÇÃO",
    "MONTES ALTOS",
    "MORROS",
    "NINA RODRIGUES",
    "NOVA COLINAS",
    "NOVA IORQUE",
    "NOVA OLINDA DO MARANHÃO",
    "OLHO D'ÁGUA DAS CUNHÃS",
    "OLINDA NOVA DO MARANHÃO",
    "PAÇO DO LUMIAR",
    "PALMEIRÂNDIA",
    "PARAIBANO",
    "PARNARAMA",
    "PASSAGEM FRANCA",
    "PASTOS BONS",
    "PAULINO NEVES",
    "PAULO RAMOS",
    "PEDREIRAS",
    "PEDRO DO ROSÁRIO",
    "PENALVA",
    "PERI MIRIM",
    "PERITORÓ",
    "PINDARÉ-MIRIM",
    "PINHEIRO",
    "PIO XII",
    "PIRAPEMAS",
    "POÇÃO DE PEDRAS",
    "PORTO FRANCO",
    "PORTO RICO DO MARANHÃO",
    "PRESIDENTE DUTRA",
    "PRESIDENTE JUSCELINO",
    "PRESIDENTE MÉDICI",
    "PRESIDENTE SARNEY",
    "PRESIDENTE VARGAS",
    "PRIMEIRA CRUZ",
    "RAPOSA",
    "RIACHÃO",
    "RIBAMAR FIQUENE",
    "ROSÁRIO",
    "SAMBAÍBA",
    "SANTA FILOMENA DO MARANHÃO",
    "SANTA HELENA",
    "SANTA INÊS",
    "SANTA LUZIA",
    "SANTA LUZIA DO PARUÁ",
    "SANTA QUITÉRIA DO MARANHÃO",
    "SANTA RITA",
    "SANTANA DO MARANHÃO",
    "SANTO AMARO DO MARANHÃO",
    "SANTO ANTÔNIO DOS LOPES",
    "SÃO BENEDITO DO RIO PRETO",
    "SÃO BENTO",
    "SÃO BERNARDO",
    "SÃO DOMINGOS DO AZEITÃO",
    "SÃO DOMINGOS DO MARANHÃO",
    "SÃO FÉLIX DE BALSAS",
    "SÃO FRANCISCO DO BREJÃO",
    "SÃO FRANCISCO DO MARANHÃO",
    "SÃO JOÃO BATISTA",
    "SÃO JOÃO DO CARÚ",
    "SÃO JOÃO DO PARAÍSO",
    "SÃO JOÃO DO SOTER",
    "SÃO JOÃO DOS PATOS",
    "SÃO JOSÉ DE RIBAMAR",
    "SÃO JOSÉ DOS BASÍLIOS",
    "SÃO LUÍS",
    "SÃO LUÍS GONZAGA DO MARANHÃO",
    "SÃO MATEUS DO MARANHÃO",
    "SÃO PEDRO DA ÁGUA BRANCA",
    "SÃO PEDRO DOS CRENTES",
    "SÃO RAIMUNDO DAS MANGABEIRAS",
    "SÃO RAIMUNDO DO DOCA BEZERRA",
    "SÃO ROBERTO",
    "SÃO VICENTE FERRER",
    "SATUBINHA",
    "SENADOR ALEXANDRE COSTA",
    "SENADOR LA ROCQUE",
    "SERRANO DO MARANHÃO",
    "SÍTIO NOVO",
    "SUCUPIRA DO NORTE",
    "SUCUPIRA DO RIACHÃO",
    "TASSO FRAGOSO",
    "TIMBIRAS",
    "TIMON",
    "TRIZIDELA DO VALE",
    "TUFILÂNDIA",
    "TUNTUM",
    "TURIAÇU",
    "TURILÂNDIA",
    "TUTÓIA",
    "URBANO SANTOS",
    "VARGEM GRANDE",
    "VIANA",
    "VILA NOVA DOS MARTÍRIOS",
    "VITÓRIA DO MEARIM",
    "VITORINO FREIRE",
    "ZÉ DOCA",
  ],
  AC: ["RIO BRANCO", "CRUZEIRO DO SUL", "SENA MADUREIRA", "TARAUACÁ", "FEIJÓ", "BRASILÉIA"],
  AL: ["MACEIÓ", "ARAPIRACA", "PALMEIRA DOS ÍNDIOS", "RIO LARGO", "PENEDO", "UNIÃO DOS PALMARES"],
  AP: ["MACAPÁ", "SANTANA", "LARANJAL DO JARI", "OIAPOQUE", "MAZAGÃO", "PORTO GRANDE"],
  AM: ["MANAUS", "PARINTINS", "ITACOATIARA", "MANACAPURU", "COARI", "TEFÉ"],
  BA: [
    "SALVADOR",
    "FEIRA DE SANTANA",
    "VITÓRIA DA CONQUISTA",
    "CAMAÇARI",
    "ITABUNA",
    "JUAZEIRO",
    "LAURO DE FREITAS",
    "ILHÉUS",
    "JEQUIÉ",
    "TEIXEIRA DE FREITAS",
  ],
  CE: [
    "FORTALEZA",
    "CAUCAIA",
    "JUAZEIRO DO NORTE",
    "MARACANAÚ",
    "SOBRAL",
    "CRATO",
    "ITAPIPOCA",
    "MARANGUAPE",
    "IGUATU",
    "QUIXADÁ",
  ],
  DF: ["BRASÍLIA"],
  ES: [
    "VITÓRIA",
    "VILA VELHA",
    "SERRA",
    "CARIACICA",
    "VIANA",
    "CACHOEIRO DE ITAPEMIRIM",
    "LINHARES",
    "SÃO MATEUS",
    "COLATINA",
    "GUARAPARI",
  ],
  GO: [
    "GOIÂNIA",
    "APARECIDA DE GOIÂNIA",
    "ANÁPOLIS",
    "RIO VERDE",
    "LUZIÂNIA",
    "ÁGUAS LINDAS DE GOIÁS",
    "VALPARAÍSO DE GOIÁS",
    "TRINDADE",
    "FORMOSA",
    "NOVO GAMA",
  ],
  MT: [
    "CUIABÁ",
    "VÁRZEA GRANDE",
    "RONDONÓPOLIS",
    "SINOP",
    "TANGARÁ DA SERRA",
    "CÁCERES",
    "SORRISO",
    "LUCAS DO RIO VERDE",
    "BARRA DO GARÇAS",
    "ALTA FLORESTA",
  ],
  MS: [
    "CAMPO GRANDE",
    "DOURADOS",
    "TRÊS LAGOAS",
    "CORUMBÁ",
    "PONTA PORÃ",
    "AQUIDAUANA",
    "PARANAÍBA",
    "NOVA ANDRADINA",
    "SIDROLÂNDIA",
    "MARACAJU",
  ],
  MG: [
    "BELO HORIZONTE",
    "UBERLÂNDIA",
    "CONTAGEM",
    "JUIZ DE FORA",
    "BETIM",
    "MONTES CLAROS",
    "RIBEIRÃO DAS NEVES",
    "UBERABA",
    "GOVERNADOR VALADARES",
    "IPATINGA",
  ],
  PA: [
    "BELÉM",
    "ANANINDEUA",
    "SANTARÉM",
    "MARABÁ",
    "CASTANHAL",
    "PARAUAPEBAS",
    "ITAITUBA",
    "CAMETÁ",
    "BRAGANÇA",
    "ABAETETUBA",
  ],
  PB: [
    "JOÃO PESSOA",
    "CAMPINA GRANDE",
    "SANTA RITA",
    "PATOS",
    "BAYEUX",
    "SOUSA",
    "CAJAZEIRAS",
    "CABEDELO",
    "GUARABIRA",
    "MAMANGUAPE",
  ],
  PR: [
    "CURITIBA",
    "LONDRINA",
    "MARINGÁ",
    "PONTA GROSSA",
    "CASCAVEL",
    "SÃO JOSÉ DOS PINHAIS",
    "FOZ DO IGUAÇU",
    "COLOMBO",
    "GUARAPUAVA",
    "PARANAGUÁ",
  ],
  PE: [
    "RECIFE",
    "JABOATÃO DOS GUARARAPES",
    "OLINDA",
    "CARUARU",
    "PETROLINA",
    "PAULISTA",
    "CABO DE SANTO AGOSTINHO",
    "CAMARAGIBE",
    "GARANHUNS",
    "VITÓRIA DE SANTO ANTÃO",
  ],
  PI: ["TERESINA", "PARNAÍBA", "PICOS", "FLORIANO", "PIRIPIRI", "CAMPO MAIOR", "BARRAS", "UNIÃO", "ALTOS", "PEDRO II"],
  RJ: [
    "RIO DE JANEIRO",
    "SÃO GONÇALO",
    "DUQUE DE CAXIAS",
    "NOVA IGUAÇU",
    "NITERÓI",
    "BELFORD ROXO",
    "SÃO JOÃO DE MERITI",
    "CAMPOS DOS GOYTACAZES",
    "PETRÓPOLIS",
    "VOLTA REDONDA",
  ],
  RN: [
    "NATAL",
    "MOSSORÓ",
    "PARNAMIRIM",
    "SÃO GONÇALO DO AMARANTE",
    "MACAÍBA",
    "CEARÁ-MIRIM",
    "CAICÓ",
    "ASSU",
    "CURRAIS NOVOS",
    "NOVA CRUZ",
  ],
  RS: [
    "PORTO ALEGRE",
    "CAXIAS DO SUL",
    "PELOTAS",
    "CANOAS",
    "SANTA MARIA",
    "GRAVATAÍ",
    "VIAMÃO",
    "NOVO HAMBURGO",
    "SÃO LEOPOLDO",
    "RIO GRANDE",
  ],
  RO: ["PORTO VELHO", "JI-PARANÁ", "ARIQUEMES", "VILHENA", "CACOAL", "JARU"],
  RR: ["BOA VISTA", "RORAINÓPOLIS", "CARACARAÍ", "ALTO ALEGRE", "MUCAJAÍ", "CANTÁ"],
  SC: [
    "FLORIANÓPOLIS",
    "JOINVILLE",
    "BLUMENAU",
    "SÃO JOSÉ",
    "CRICIÚMA",
    "CHAPECÓ",
    "ITAJAÍ",
    "JARAGUÁ DO SUL",
    "LAGES",
    "PALHOÇA",
  ],
  SP: [
    "SÃO PAULO",
    "GUARULHOS",
    "CAMPINAS",
    "SÃO BERNARDO DO CAMPO",
    "SANTO ANDRÉ",
    "OSASCO",
    "SÃO JOSÉ DOS CAMPOS",
    "RIBEIRÃO PRETO",
    "SOROCABA",
    "MAUÁ",
  ],
  SE: ["ARACAJU", "NOSSA SENHORA DO SOCORRO", "LAGARTO", "ITABAIANA", "ESTÂNCIA", "SÃO CRISTÓVÃO"],
  TO: ["PALMAS", "ARAGUAÍNA", "GURUPI", "PORTO NACIONAL", "PARAÍSO DO TOCANTINS", "COLINAS DO TOCANTINS"],
}
